name: Lint & Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.9", "3.8"]
        py-algorand-sdk-version: ["1.1.x", "1.2.x", "1.3.x", "1.4.x", "1.5.x", "1.6.x", "1.7.x", "1.8.x", "1.9.x", "1.1x", "1.2x"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black py-algorand-sdk==${{ matrix.py-algorand-sdk-version }}

      - name: Run flake8
        run: flake8 ${{ github.workspace }} --ignore=E501,F403,F405,E126,E121,W503,E203

      - name: Run Black
        run: black ${{ github.workspace }} --check

      - name: Run Unit tests
        run: python -m unittest
